package model

type InkeAutoGenerated struct {
	ErrorCode int    `json:"error_code"`
	Message   string `json:"message"`
	Data      struct {
		MediaInfo struct {
			Nick        string `json:"nick"`
			Portrait    string `json:"portrait"`
			InkeID      int    `json:"inke_id"`
			Level       int    `json:"level"`
			Gender      int    `json:"gender"`
			GenderImg   string `json:"gender_img"`
			Area        string `json:"area"`
			Description string `json:"description"`
			LevelImg    string `json:"level_img"`
		} `json:"media_info"`
		File struct {
			Status      int    `json:"status"`
			RecordURL   string `json:"record_url"`
			OnlineUsers int    `json:"online_users"`
			Title       string `json:"title"`
			Pic         string `json:"pic"`
			City        string `json:"city"`
		} `json:"file"`
		Records   []interface{} `json:"records"`
		Status    int           `json:"status"`
		Portrait  string        `json:"portrait"`
		Point     int           `json:"point"`
		SioIP     string        `json:"sio_ip"`
		Liveid    string        `json:"liveid"`
		LiveUID   string        `json:"live_uid"`
		IsFollow  int           `json:"is_follow"`
		WeiboURL  string        `json:"weibo_url"`
		WeixinURL string        `json:"weixin_url"`
		Sec       string        `json:"sec"`
		ViewUID   string        `json:"view_uid"`
		Nonce     string        `json:"nonce"`
		Time      int           `json:"time"`
		SioMd5    string        `json:"sio_md5"`
		ViewNick  string        `json:"view_nick"`
		Token     string        `json:"token"`
		TokenTime string        `json:"token_time"`
		Origin    interface{}   `json:"origin"`
		IsLogin   int           `json:"is_login"`
		SioURL    string        `json:"sio_url"`
		LiveAddr  []struct {
			Liveid         string `json:"liveid"`
			StreamAddr     string `json:"stream_addr"`
			HlsStreamAddr  string `json:"hls_stream_addr"`
			RtmpStreamAddr string `json:"rtmp_stream_addr"`
		} `json:"live_addr"`
		LiveType    string `json:"live_type"`
		SubLiveType string `json:"sub_live_type"`
		LiveName    string `json:"live_name"`
	} `json:"data"`
}
