package model

type KsLiveDetailAutoGenerated struct {
	Data struct {
		WebLiveDetail struct {
			LiveStream struct {
				Caption  string `json:"caption"`
				PlayUrls []struct {
					Quality string `json:"quality"`
					URL     string `json:"url"`
				} `json:"playUrls"`
			} `json:"liveStream"`
		} `json:"webLiveDetail"`
	} `json:"data"`
}

type KsUserInfoAutoGenerated struct {
	Data struct {
		UserInfo struct {
			Name   string `json:"name"`
			Living bool   `json:"living"`
		} `json:"userInfo"`
	} `json:"data"`
}
