package model

type KsLiveDetailAutoGenerated struct {
	Data struct {
		WebLiveDetail struct {
			LiveStream struct {
				Caption  string `json:"caption"`
				PlayUrls []struct {
					Quality string `json:"quality"`
					URL     string `json:"url"`
				} `json:"playUrls"`
			} `json:"liveStream"`
		} `json:"webLiveDetail"`
	} `json:"data"`
}
